# Generated by Django 4.1.3 on 2022-11-30 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=9, unique=True, verbose_name='NIF')),
                ('business_name', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Empresa')),
                ('country', models.CharField(max_length=50, verbose_name='Pais')),
                ('province', models.CharField(max_length=200, verbose_name='Provincia')),
                ('town', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('postal_code', models.CharField(max_length=100, verbose_name='Código postal')),
                ('phone', models.IntegerField(verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('lot', models.IntegerField(verbose_name='Lote')),
                ('type', models.CharField(max_length=200, verbose_name='Tipo')),
                ('reference', models.CharField(max_length=200, verbose_name='Referencia')),
                ('reception_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso recepción')),
                ('starting_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso inicial')),
                ('w_b_d', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso antes de taladro')),
                ('w_a_d', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso después de taladro')),
                ('observations', models.TextField(null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'db_table': 'entry',
                'ordering': ['id'],
            },
        ),
    ]
